### ISSUE TITLE
Player js code is prepended to all webpack files

### ISSUE THREAD

**Issue by Valandur** [brightcove/player-loader-webpack-plugin#10]
https://github.com/brightcove/player-loader-webpack-plugin/blob/c51be811c7da0e671f05489ea4509a770c9d544c/src/index.js#L36

This line causes the player's js code to be prepended to all webpack files, and when using for example [the mini-css plugin from webpack](https://github.com/webpack-contrib/mini-css-extract-plugin), the js source is prepended to all CSS files, making them invalid.

**Comment by misteroneill** [comment]
Whoops! Thanks for the report @Valandur, we'll take a look!

**Comment by brandonocasey** [comment]
Should be fixed in 1.1.0

**Comment by Valandur** [comment]
Just as a quick note: I believe [in the readme](https://github.com/brightcove/player-loader-webpack-plugin#prependto) it should say "_to the first file with a js extension_", instead of "_to all files with a js extension_"

Thank you for the quick fix!

**Comment by misteroneill** [comment]
Thanks again, @Valandur!
